name: mohe_app_1_x_x
description: "A new Flutter project."
publish_to: 'none'
version: 4.0.0+30

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  http: ^1.2.2
  provider: ^6.1.2
  flutter_secure_storage: ^9.2.2
  image_picker: ^1.1.2          # this package "path_provider" and "path" is used in "image_avatar_input.dart" and discussed there
  image_picker_for_web: ^3.0.5
  path_provider: ^2.1.4
  path: ^1.9.0
  # location: ^7.0.0              # to get the current location LatLng, WHILE "google_maps_flutter" has this ability, BUT I didn't preferred
  # google_maps_flutter: ^2.9.0   # it is google map
  cached_network_image: ^3.4.0
  flutter_cache_manager: ^3.4.1 # we use it to customCachManager with "cached_network_image", and cached_network_image is builded base on it: BUT the package originally is used  to download and cache files in the cache directory of the app
  flutter_sound: ^9.23.1
  permission_handler: ^11.3.1
  audioplayers: ^6.1.0
  # fl_chart: ^0.69.0
  flutter_svg: ^2.0.10+1
  font_awesome_flutter: ^10.7.0
  google_fonts: ^6.2.1
  hive: ^2.2.3                  # Fast, key-value & Secure NoSQL Database
  hive_flutter: ^1.1.0          # if you work with hive, you have to install this package also
  http_parser: ^4.0.2
  url_launcher: ^6.3.0
  # carousel_slider: ^5.0.0
  intl: ^0.19.0
  mobile_scanner: ^6.0.0
  flutter_native_splash: ^2.4.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

  # hive database generators
  hive_generator: ^2.0.1        # flutter pub add --dev hive_generator
  build_runner: ^2.4.11         # flutter pub add --dev build_runner
  flutter_launcher_icons: ^0.14.3

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icons/app_logo.png"
  # min_sdk_android: 21 # android min sdk min:16, default 21

flutter_native_splash:
  color: "#F1F1F1"  # Background color of the splash screen (KScaffoldBackgroundColor)
  image: assets/icons/app_logo.png  # Path to your splash image
  android: true
  ios: true
  # run this command in terminal at last step>> flutter pub run flutter_native_splash:create

flutter:
  uses-material-design: true

   # To add assets to your application, add an assets section, like this:
  assets:
    - assets/locales/
    - assets/images/
    - assets/icons/
    - assets/sounds/
  #   - images/a_dot_ham.jpeg

  fonts:
    - family: Dela Gothic One
      fonts:
        - asset: assets/fonts/DelaGothicOne-Regular.ttf
  #       - asset: fonts/Raleway-Italic.ttf
  #         style: italic
    - family: Itim
      fonts:
        - asset: assets/fonts/Itim-Regular.ttf
  #       - asset: fonts/RobotoMono-Bold.ttf
  #        weight: 700 

    - family: Plex Sans Bold
      fonts:
        - asset: assets/fonts/IBMPlexSansArabic-Bold.ttf
  #       - asset: fonts/RobotoMono-Bold.ttf
  #        weight: 700 
    - family: Plex Sans Regular
      fonts:
        - asset: assets/fonts/IBMPlexSansArabic-Regular.ttf
  #       - asset: fonts/RobotoMono-Bold.ttf
  #        weight: 700 
    - family: Plex Sans SemiMedium
      fonts:
        - asset: assets/fonts/IBMPlexSansArabic-Medium.ttf
  #       - asset: fonts/RobotoMono-Bold.ttf
  #        weight: 700
    - family: Plex Sans Bold
      fonts:
        - asset: assets/fonts/IBMPlexSansArabic-SemiBold.ttf
  #       - asset: fonts/RobotoMono-Bold.ttf
  #        weight: 700  
    
